###user routes 

GET http://localhost:3000/notes

###

GET http://localhost:3000/todos/63078362e14ab0eea946f547

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "edriss",
  "email": "edriss@gmail.com",
  "password": "something"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "edr",
  "email": "edriss@gail.com",
  "password": "$2b$10$7gX3gwUXJc8FS8Uxln7Fe5OyGKBYBlZeQmTMd8b3y/9iCJJgiPZS"
}

###

DELETE  http://localhost:3000/todos/63078362e14ab0eea946f547

###

PATCH http://localhost:3000/todos/63078362e14ab0eea946f547
Content-Type: application/json

{
  "todo": "do nothing"
}